### ISSUE TITLE
Termostat

### ISSUE THREAD

**Issue by system39** [FredBlo/node-red-contrib-myhome-bticino-v2#10]
Hi
How can I set "setTemperature" parametr with node MH Thermo Zone? Any exampless?

**Comment by FredBlo** [comment]
Hi,
Not sure what you already tried actually...
The `.setTemperature` is only used in the returned payload (node's output) and represents the current 'set point' defined in manual mode (=the temperature to be reached).

To change the temperature set point, you can simply input the node with a value, or use an object and set the temperature value as `.state` (in both cases, do not forget to have a matching `msg.topic` set as described in doc / info).

Some sample to make it easier to start with :
```
[{"id":"319d7223.170ba6","type":"myhome-thermo-zone","z":"125a7426.3ccc94","name":"Living (F455)","zoneid":"1","topic":"livingroom","gateway":"a4e23617.d0c288","smartfilter":true,"skipevents":true,"isstatusrequest":false,"output2_name":"","output2_type":"text_state","x":520,"y":540,"wires":[["6e643b95.74653c"],[]]},{"id":"af76b453.960e48","type":"inject","z":"125a7426.3ccc94","name":"Adv mode : Set Manual = 21°C","props":[{"p":"payload.state","v":"21","vt":"str"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"cmd/livingroom","x":250,"y":520,"wires":[["319d7223.170ba6"]]},{"id":"16902a10.d381ce","type":"inject","z":"125a7426.3ccc94","name":"Get current state","props":[{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"state/livingroom","x":300,"y":560,"wires":[["319d7223.170ba6"]]},{"id":"1ba9c187.9511b6","type":"inject","z":"125a7426.3ccc94","name":"EASY mode : Set Manual = 21°C","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"cmd/livingroom","payload":"21","payloadType":"str","x":250,"y":480,"wires":[["319d7223.170ba6"]]},{"id":"6e643b95.74653c","type":"debug","z":"125a7426.3ccc94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":710,"y":520,"wires":[]},{"id":"a4e23617.d0c288","type":"myhome-gateway","name":"F-455","host":"192.168.0.210","port":"20000","pass":"12345","timeout":"600","log_in_lights":false,"log_in_shutters":false,"log_in_temperature":false,"log_in_energy":false,"log_in_others":false,"log_out_cmd":false}]
```

Enjoy :-)

**Comment by FredBlo** [comment]
@system39 , any update on your experience with the nodes ?

**Comment by system39** [comment]
Thank you, for your request! But I can't change the temperature set point  by node. MH inject node working fine

**Comment by FredBlo** [comment]
Hi @system39 ,

Can you provide me with some more info so I can check whether I can improve the node ?
- which gateway are you using ?
- when you try to change the temperature using the node, which output (on output n°1) do you receive ? (mainly content of   `command_sent` and `command_responses`
- which command(s) do you send through the MH Inject node which works OK for you ?

Tks !

**Comment by system39** [comment]
Hi @FredBlo 

I'm use MH202

Here my nodes:
`[{"id":"a3b5c24cd7f53d36","type":"myhome-commandsession","z":"51c5a0dc0336ad09","name":"inject","gateway":"a009d1d918a0815f","intercommandsdelay":"","x":370,"y":40,"wires":[["9d03cfb2995e5b67"]]},{"id":"25500b63d4b129fe","type":"inject","z":"51c5a0dc0336ad09","name":"","props":[{"p":"payload"}],"repeat":"61","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"*#4*1##","payloadType":"str","x":180,"y":40,"wires":[["a3b5c24cd7f53d36"]]},{"id":"9d03cfb2995e5b67","type":"change","z":"51c5a0dc0336ad09","name":"change","rules":[{"t":"move","p":"payload.command_responses","pt":"msg","to":"responses","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":540,"y":40,"wires":[["87c4eb10c8154b32","461dae7bda86a26e"]]},{"id":"87c4eb10c8154b32","type":"function","z":"51c5a0dc0336ad09","name":"","func":"var input = Number(msg.responses[4].substr(9,3));\nvar output = input / 10;\nreturn {payload:output};","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":740,"y":40,"wires":[["13479fcea6260704"]]},{"id":"461dae7bda86a26e","type":"function","z":"51c5a0dc0336ad09","name":"","func":"var input = Number(msg.responses[1].substr(10,3));\nvar output = input / 10;\nreturn {payload:output};","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":740,"y":120,"wires":[["3833eb4b7c1c87cf"]]},{"id":"0dce95e2339523bc","type":"openhab2-in2","z":"51c5a0dc0336ad09","name":"","controller":"20582be639fd7aca","itemname":"BTut01","topic":"","initialstate":false,"whenupdated":true,"whencommand":true,"whenchanged":false,"changedfrom":"","changedto":"","x":170,"y":120,"wires":[["cd8b9e755587e686"]]},{"id":"cd8b9e755587e686","type":"function","z":"51c5a0dc0336ad09","name":"","func":"var input = msg.payload * 10;\nvar output = \"*#4*1*#14*0\"+input+\"*3##\"\nreturn {payload:output};","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":320,"y":120,"wires":[["4e1f7c3654cd0e8d"]]},{"id":"4e1f7c3654cd0e8d","type":"myhome-commandsession","z":"51c5a0dc0336ad09","name":"inject","gateway":"a009d1d918a0815f","intercommandsdelay":"","x":470,"y":120,"wires":[[]]},{"id":"13479fcea6260704","type":"openhab2-out2","z":"51c5a0dc0336ad09","name":"","controller":"20582be639fd7aca","itemname":"BTt01","topic":"ItemUpdate","payload":"","onlywhenchanged":false,"x":930,"y":40,"wires":[]},{"id":"3833eb4b7c1c87cf","type":"openhab2-out2","z":"51c5a0dc0336ad09","name":"","controller":"20582be639fd7aca","itemname":"BTut01","topic":"ItemUpdate","payload":"","onlywhenchanged":false,"x":940,"y":120,"wires":[]},{"id":"a009d1d918a0815f","type":"myhome-gateway","name":"MH202","host":"192.168.55.253","port":"20000","pass":"12345","timeout":"600","log_in_lights":true,"log_in_shutters":true,"log_in_temperature":true,"log_in_scenario":true,"log_in_energy":true,"log_in_others":true,"log_out_cmd":true},{"id":"20582be639fd7aca","type":"openhab2-controller2","name":"openHAB","protocol":"http","host":"127.0.0.1","port":"8080","path":"","username":"","password":"","ohversion":"v2","token":""}]`

**Comment by FredBlo** [comment]
Hi @system39 

If I understand your flow correctly, you change manual temperature using an inject on your function :
`var output = "*#4*1*#14*0"+input+"*3##"`

What's interesting is that this call is different from what Bticino documents, since it should be :
`var output = "*#4*#1*#14*0"+input+"*3##"`  (the added # before 1)
![image](https://user-images.githubusercontent.com/78979088/132844589-2a7e4dbc-78bf-434b-845e-4018a252856b.png)

Could you confirm to me that the 'theoretically working' one (with the added #) fails on your side?
I will further try the one without # on my side :-)

**Comment by system39** [comment]
Hi @FredBlo 
I’m read bticino documents too. And yes, example in document not working. Without # work fine. why? I don’t know)

**Comment by FredBlo** [comment]
Hi @system39 

I have a MH202 on my bus too. I tested and both commands are OK :
- `*#4*#1*#14*0190*3##`
- `*#4*1*#14*0190*3##`

Which is the firmware version of your MH202 ?
(mine is 1.0.24, latest available as far as I know)
![image](https://user-images.githubusercontent.com/78979088/133134416-3a0e159d-5c74-426a-8000-ce54f236168d.png)

I also tested on the other gateways I can test on (MyHomeServer1, F459 and F455).
It's interesting to note that all of them seem to react the same way on both commands (i.e. with or without the extra '#')

**Comment by system39** [comment]
Hi @FredBlo

My FW version in 1.0.24 too
