### ISSUE TITLE
F454

### ISSUE THREAD

**Issue by stefanorossiitaly** [FredBlo/node-red-contrib-myhome-bticino-v2#22]
I have the F454 webserver. Does this module also work? because I can't connect I get the following error:
"↵↵---------------------------------------------------------------------↵Your flow credentials file is encrypted using a system-generated key.↵↵If the system-generated key is lost for any reason, your credentials↵file will not be recoverable, you will have to delete it and re-enter↵your credentials.↵↵You should set your own key using the 'credentialSecret' option in↵your settings file. Node-RED will then re-encrypt your credentials↵file using your chosen key the next time you deploy a change.↵---------------------------------------------------------------------↵"
26/12/2023, 17:36:23
msg : string[31]
"Encrypted credentials not found"
26/12/2023, 17:36:23[node: F-455](http://localhost:1880/#)
msg : string[78]
"gateway connection : disconnected from host, last known state was 'connected'."

**Comment by FredBlo** [comment]
Hi,

In your log you only have the lines you sent ? I would expect something between flow credentials info and gateway connection actually, like 

23 Dec 16:09:47 - [info] Server now running at http://127.0.0.1:1880/
23 Dec 16:09:47 - [info] Starting flows
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : instanciating client... (attempt #1)
23 Dec 16:09:47 - [info] Started flows
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : trying to connect to host...(192.168.0.212:20000)
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : connected to host (192.168.0.212:20000), initiating TCP monitoring...
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : handshake acknowledged, asking for authentication if required...
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : request to authenticate acknowledged, authenticating using basic password check...
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : Connection successful !
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : gathering status of all connected lights within a few seconds...

?

**Comment by stefanorossiitaly** [comment]
I use the F454

 

Your flow credentials file is encrypted using a system-generated key.

 

If the system-generated key is lost for any reason, your credentials

file will not be recoverable, you will have to delete it and re-enter

your credentials.

 

You should set your own key using the 'credentialSecret' option in

your settings file. Node-RED will then re-encrypt your credentials

file using your chosen key the next time you deploy a change.

---------------------------------------------------------------------

26/12/2023, 23:27:01msg : string[31]

"Encrypted credentials not found"

26/12/2023, 23:27:01node: F-455 <http://127.0.0.1:1880/> msg : string[78]

"gateway connection : disconnected from host, last known state was 'connected'.

 

 

 

 

Da: FredBlo ***@***.***> 
Inviato: martedì 26 dicembre 2023 20:27
A: FredBlo/node-red-contrib-myhome-bticino-v2 ***@***.***>
Cc: stefanorossiitaly ***@***.***>; Author ***@***.***>
Oggetto: Re: [FredBlo/node-red-contrib-myhome-bticino-v2] F454 (Issue #22)

 

Hi,

In your log you only have the lines you sent ? I would expect something between flow credentials info and gateway connection actually, like

23 Dec 16:09:47 - [info] Server now running at http://127.0.0.1:1880/
23 Dec 16:09:47 - [info] Starting flows
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : instanciating client... (attempt #1 <https://github.com/FredBlo/node-red-contrib-myhome-bticino-v2/discussions/1> )
23 Dec 16:09:47 - [info] Started flows
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : trying to connect to host...(192.168.0.212:20000)
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : connected to host (192.168.0.212:20000), initiating TCP monitoring...
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : handshake acknowledged, asking for authentication if required...
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : request to authenticate acknowledged, authenticating using basic password check...
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : Connection successful !
23 Dec 16:09:47 - [info] [myhome-gateway:F459] gateway connection : gathering status of all connected lights within a few seconds...

?

**Comment by FredBlo** [comment]
Hi,

The F454 is described as a gateway and it is the same generation (~release date) as MH201, only 1,5 year older than F455...
It is announced by Bticino as a gateway, so it should work.

The 'credentials warning' message you have is from Node-RED and is not a problem as such... the second part is maybe more of a concern '"Encrypted credentials not found"'
But your log looks weird to me anyway... I will need a bit more info
- which **version of Node-RED** are you running ? On which device ?
- how is you gateway configured wrt **security** : no password (=white-listed IP address), OPEN password or HMAC password ?
- can you enable **'debug' logging level** in your Node-RED 'settings.js' file and sent me log content after restarting ?
![image](https://github.com/FredBlo/node-red-contrib-myhome-bticino-v2/assets/78979088/3180657f-db44-4ffc-991f-7eff7a0bfdf7)
- are you able to connect to your gateway **using a PC** with Bticino software, in command and monitoring mode ? (OpenWebNet client, can be found [here](https://developer.legrand.com/Documentation/client-download/))
- can you provide a **sample of your flow** (by exporting a selected MyHome node & its linked one, this will also include the gateway node

Let me know :-)

**Comment by stefanorossiitaly** [comment]
I was able to use your example. 

Very nice. 

I would like to use it in my system. 

I'm not very expert. I would like to use it to control home assistant devices or entities. I believe you should use the MQTT protocol. Or is it no use?

If yes, can you send me an example of an MQTT configuration that communicates with your NOD-RED system. My system is very large I will send you the MYHome Suite file. Thank you

 

 

Da: FredBlo ***@***.***> 
Inviato: mercoledì 27 dicembre 2023 11:02
A: FredBlo/node-red-contrib-myhome-bticino-v2 ***@***.***>
Cc: stefanorossiitaly ***@***.***>; Author ***@***.***>
Oggetto: Re: [FredBlo/node-red-contrib-myhome-bticino-v2] F454 (Issue #22)

 

Hi,

The F454 is described as a gateway and it is the same generation (~release date) as MH201, only 1,5 year older than F455...
It is announced by Bticino as a gateway, so it should work.

The 'credentials warning' message you have is from Node-RED and is not a problem as such... the second part is maybe more of a concern '"Encrypted credentials not found"'
But your log looks weird to me anyway... I will need a bit more info

*	which version of Node-RED are you running ? On which device ?
*	how is you gateway configured wrt security : no password (=white-listed IP address), OPEN password or HMAC password ?
*	can you enable 'debug' logging level in your Node-RED 'settings.js' file and sent me log content after restarting ?
image.png (view on web) <https://github.com/FredBlo/node-red-contrib-myhome-bticino-v2/assets/78979088/3180657f-db44-4ffc-991f-7eff7a0bfdf7> 
*	are you able to connect to your gateway using a PC with Bticino software, in command and monitoring mode ? (OpenWebNet client, can be found here <https://developer.legrand.com/Documentation/client-download/> )
*	can you provide a sample of your flow (by exporting a selected MyHome node & its linked one, this will also include the gateway node

Let me know :-)

**Comment by FredBlo** [comment]
So I understand you were able to connect to your gateway then :-)

I do not use MQTT, but I am sure finding a sample flow -to base your on- should be quite easy on standard subflows on nodered.org ([this one for example](https://flows.nodered.org/flow/0e13796852a29cd0b4840ce67a743e3a)).
Once you have the incoming/outgoing info in node-RED, using nodes is quite straightforward based on sample flows provided.

The MyHome Suite file is not required (all you need to configure you nodes is the 'AP' number of your light points, shutters,...)

I am however wondering : if you are already using a home assistant 'server', why don't you add a plugin directly in there (such as this [one)](https://community.home-assistant.io/t/legrand-bticino-myhome/229337) instead of re-mapping those to a secondary instance running node-RED ?

**Comment by stefanorossiitaly** [comment]
I tried using the one from anotherjulien Julien. 

Unfortunately he doesn't manage the backbones well (#4#backbone). 

To be clear, F422 Bticino. There is an error.

 

Could you give me an example of a sensor visible from HA that is written and read by your application?.

Thank you

 

Stefano Rossi

 

 

Da: FredBlo ***@***.***> 
Inviato: venerdì 29 dicembre 2023 11:52
A: FredBlo/node-red-contrib-myhome-bticino-v2 ***@***.***>
Cc: stefanorossiitaly ***@***.***>; Author ***@***.***>
Oggetto: Re: [FredBlo/node-red-contrib-myhome-bticino-v2] F454 (Issue #22)

 

So I understand you were able to connect to your gateway then :-)

I do not use MQTT, but I am sure finding a sample flow -to base your on- should be quite easy on standard subflows on nodered.org (this one for example <https://flows.nodered.org/flow/0e13796852a29cd0b4840ce67a743e3a> ).
Once you have the incoming/outgoing info in node-RED, using nodes is quite straightforward based on sample flows provided.

The MyHome Suite file is not required (all you need to configure you nodes is the 'AP' number of your light points, shutters,...)

I am however wondering : if you are already using a home assistant 'server', why don't you add a plugin directly in there (such as this one) <https://community.home-assistant.io/t/legrand-bticino-myhome/229337>  instead of re-mapping those to a secondary instance running node-RED ?

**Comment by FredBlo** [comment]
OK, I understand, multiple risers is not something I included from the beginning in my nodes set (and I personally have a F422 but is configured in 'physical expansion' mode, so remains 'transparent')

I do not use (nor have any experience) with HA, so I will not be able to assist you on this one, sorry...
I personally decided to have all running on node-RED to avoid multiple services..

But I would try to search on a sensor integration between HA and a HUE or HomeKit runnning on Node-RED... I think this is a more common case (Bticino is not as widespread as these 2 ;-) )...

Hope you find your way through (and would be interesting to post your final solution so others can use it afterwards : -) )
